### ISSUE TITLE
How to find / run / install Ollama

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop-rdx-open-webui-archive#10]
This issue replaces rancher-sandbox/rancher-desktop-rdx-open-webui2#6

1. When the extension is loaded, it checks if the Ollama port is open. If it is, it will use the currently running instance.

2. If the port is currently closed, the extension will look for an installed binary in some common/default install locations, like `/usr/local/bin/ollama`. If it finds it, it will start its own instance using that binary.

3. Otherwise it will download and install a binary inside the extension directory, and then run the instance from there.

If the extension is uninstalled, then the Ollama binary inside the extension directory (case 3 above) will automatically be deleted as well. All other binaries will not be touched because we did not install them. The running Ollama instance must be stopped before the extension is uninstalled.

In case 2 and case 3 Rancher Desktop will need to stop the Ollama process when Rancher Desktop itself is terminated (see rancher-sandbox/rancher-desktop-rdx-open-webui#4).

### Notes

There is never a need to show an additional installation screen to ask for an install location.

If there is an existing Ollama installation in a non-default location, and it is not running, then that binary will be ignored (we don't know about it), and the extension will download and install its own binary (case 3).

On Linux the default installation runs under a separate `ollama` user and also stores the models in a location only accessible by that user. When the user stops the ollama service, then the extension will run its own subprocess (case 2). However, this subprocess will run under the current user, so will create `~/.ollama` to store certs and models. The models downloaded using the `ollama` user are not visible and cannot be used. This is confusing for the user, but hopefully it is unlikely that the user will frequently stop/start the service running under the `ollama` user.

**Comment by mook-as** [comment]
To summarize desired changes (to see if I've got things right):

- Drop the ability to install to arbitrary locations; always install into the extension directory.

Linux/systemd shouldn't be an issue, because the unit they install is:
https://github.com/ollama/ollama/blob/f40bb398f6423ae82386820f0abfe279045771b7/scripts/install.sh#L124-L137
That says to start the service after network turns on, and restart it three seconds after it quits. So I assume the intended behaviour is that it's _always_ running, so we don't need to manage it at all.  That is, it should _always_ fall under case ① above.

**Comment by mook-as** [comment]
Hmm, actually having implemented this, wouldn't it make sense then to go back to installing ollama (if needed) on extension install, instead of making the user trigger it by clicking on the only button available? It's not like there's any options to set.

**Comment by jandubois** [comment]
> Hmm, actually having implemented this, wouldn't it make sense then to go back to installing ollama (if needed) on extension install, instead of making the user trigger it by clicking on the only button available?

Yes, please, that's what I meant by:

> There is never a need to show an additional installation screen to ask for an install location.

Well, I didn't think about moving the installation to the extension installation, but that is good because otherwise there would be an awkward delay when you open the extension and it still needs to download Ollama.
