### ISSUE TITLE
Enable Web Search option is not visible within the extension view

### ISSUE THREAD

**Issue by gunamata** [rancher-sandbox/rancher-desktop-rdx-open-webui-archive#17]
The Web Search option is not visible within the extension page view. The option is visible when the open webui is accessed via browser at localhost:3000.

Within the Extension:

![image](https://github.com/user-attachments/assets/8a5821a0-6b3b-460e-8ef6-6474be398cdd)

Within the browser:

![image](https://github.com/user-attachments/assets/c6350702-10ec-4e34-8d7e-e4d701c1a1cb)

**Comment by mook-as** [comment]
I don't understand how it's working in the browser.
That's enabled if you set a query parameter:
https://github.com/open-webui/open-webui/blob/caeca9d300b55d3ce5794e498e5424e72ffae177/src/lib/components/chat/Chat.svelte#L351
That doesn't seem to ever be set within in openwebui repo.
