### ISSUE TITLE
Use searxing as the default web search option

### ISSUE THREAD

**Issue by gunamata** [rancher-sandbox/rancher-desktop-rdx-open-webui-archive#20]
open webui provides multiple options for web search out of them `searxing` (which the extension sets up) and `duckduckgo` are two options that do not need a api key. Out of `searxing` and `duckduckgo`, `searxing` provided better, relevant search results so use it as default. Users can always switch to a different web search option if they want via the Admin settings.

**Comment by jandubois** [comment]
Fixed by #21
