### ISSUE TITLE
Verify that we are allowed to use the open-webui icon for our extension

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop-rdx-open-webui-archive#4]

**Comment by gunamata** [comment]
Given that we are adding an extension to use Open WebUI as a feature and also the https://openwebui.com/ doesn't have any policy about the logo usage and such, it seems to be okay to use the logo. We will anyways mention in the docs that open-webui is a community project and the extension provides a way to use it within Rancher Desktop.
